Added SandBoxDemo for SingleDropdownList
appbaseio/reactive-manual pull request #104
Opened 2018-11-12 21:11 UTC by divyanshu-rawat

Here is the link to the Demo - https://codesandbox.io/s/m9j1k1rq9p

2018-11-12 21:15 UTC, divyanshu-rawat commented
@bietkul please review this 👍

2018-11-13 20:05 UTC, bietkul commented on content/docs/list-components/SingleDropdownList.md
> +
@divyanshu-rawat Please add SelectedFilters in all codesanbox demos.
And keep the same layout in full screen mode as we have in storybook demos( in this example dropdown list covers the results ).

2018-11-13 20:06 UTC, bietkul reviewed
@divyanshu-rawat Please add SelectedFilters in all codesanbox demos.
And keep the same layout in full screen mode as we have in storybook demos( in this example dropdown list covers the results )

2018-11-13 23:24 UTC, divyanshu-rawat commented
@bietkul Updated the PR 👍

2018-11-14 08:34 UTC, bietkul commented
I'm not able to find the changes in codesandbox demo.

2018-11-14 08:45 UTC, bietkul requested changes
You need to update the nav.yml so we can access the demos from sidebar.

2018-11-14 09:05 UTC, divyanshu-rawat commented
@bietkul sandbox updated - https://codesandbox.io/s/ly6w2k7y27
it wasn't saved.

2018-11-14 10:01 UTC, jyash97 commented
`nav.yml` is file used to define the items and their navigation that are present on the right sidebar.

check this [file](https://github.com/appbaseio/reactive-manual/blob/v1-vue/content/docs/list-components/nav.yml)
On line 16 we have `demo` item and its link i.e href attribute.

2018-11-14 16:50 UTC, merged