Vue:Single Range Syntax Update
appbaseio/reactive-manual pull request #111
Opened 2018-11-27 21:53 UTC by divyanshu-rawat

Syntax correction for vue.js.

2018-11-27 21:57 UTC, divyanshu-rawat commented
@bietkul Please review this 👍

2018-11-29 11:55 UTC, bietkul requested changes

2018-11-29 11:55 UTC, bietkul commented on content/docs/range-components/SingleRange.md
> +    is an event which accepts component's current **value** as a parameter. It is called everytime the component's value changes. This event is handy in cases where you want to generate a side-effect
Change MultiRange to SingleRange.

2018-11-29 12:07 UTC, divyanshu-rawat commented on content/docs/range-components/SingleRange.md
> +    is an event which accepts component's current **value** as a parameter. It is called everytime the component's value changes. This event is handy in cases where you want to generate a side-effect
Updated

2018-11-29 12:10 UTC, bietkul approved these changes

2018-11-29 12:15 UTC, merged